// @ts-nocheck
// Blueprint 2.0 question + solution catalog — shared by seed script and app instrumentation

interface OptionDef {
  externalId: string;
  textDe: string;
  points: number;
  isExclusive?: boolean;
  signalCategory?: string | null;
  signalValue?: number;
  /** Lösungen, die genau diese Antwort auslöst. */
  solutionRefs?: string[];
  order: number;
}

interface QuestionDef {
  externalId: string;
  moduleNumber: number;
  groupCode?: string;
  area: string;
  phase: string;
  questionType: "A" | "B" | "C";
  isGating?: boolean;
  isFollowUp?: boolean;
  parentExternalId?: string;
  internalWeight?: number;
  activationConds?: object[];
  order: number;
  isRequired: boolean;
  intent: string;
  questionDe: string;
  options: OptionDef[];
}


// ─── Activation condition helpers ────────────────────────────────────────────

export const HAS_EMPLOYEES = [
  { type: "M1_OPTION_NOT_IN", ref: "M1.2", optionExternalIds: ["M1.2-OPT-1"] },
];

export const HAS_FIELD_OR_SHIFT = [
  {
    type: "M1_OPTION_IN",
    ref: "M1.4",
    optionExternalIds: ["M1.4-OPT-2", "M1.4-OPT-3", "M1.4-OPT-5"],
  },
];

export const HAS_FIELD_OR_SHIFT_EMPLOYEES = [
  {
    type: "M1_OPTION_IN",
    ref: "M1.4",
    optionExternalIds: ["M1.4-OPT-2", "M1.4-OPT-3", "M1.4-OPT-5"],
  },
  { type: "M1_OPTION_NOT_IN", ref: "M1.2", optionExternalIds: ["M1.2-OPT-1"] },
];

// ─── QUESTION CATALOG ────────────────────────────────────────────────────────

export const QUESTIONS: QuestionDef[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 1 – Unternehmensprofil (Typ A, kein Score)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M1.1",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 100,
    isRequired: true,
    intent: "Branche des Unternehmens erfassen für Branching-Logik und Empfehlungskontext",
    questionDe: "In welcher Branche ist Ihr Unternehmen hauptsächlich tätig?",
    options: [
      { externalId: "M1.1-OPT-1", textDe: "Pflege / Soziale Dienste", points: 0, order: 1 },
      { externalId: "M1.1-OPT-2", textDe: "Handwerk / Baugewerbe", points: 0, order: 2 },
      { externalId: "M1.1-OPT-3", textDe: "Gebäudereinigung / Facility Management", points: 0, order: 3 },
      { externalId: "M1.1-OPT-4", textDe: "Sicherheitsdienst / Wachschutz", points: 0, order: 4 },
      { externalId: "M1.1-OPT-5", textDe: "Gastronomie / Catering", points: 0, order: 5 },
      { externalId: "M1.1-OPT-6", textDe: "Logistik / Transport", points: 0, order: 6 },
      { externalId: "M1.1-OPT-7", textDe: "Dienstleistung (allgemein)", points: 0, order: 7 },
      { externalId: "M1.1-OPT-8", textDe: "Produktion / Fertigung", points: 0, order: 8 },
      { externalId: "M1.1-OPT-9", textDe: "Sonstiges (bitte angeben)", points: 0, order: 9 },
    ],
  },
  {
    externalId: "M1.2",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 101,
    isRequired: true,
    intent: "Mitarbeiteranzahl erfassen — bestimmt Aktivierung von M5.2, M5.3 und M8",
    questionDe: "Wie viele angestellte Mitarbeitende hat Ihr Unternehmen aktuell?",
    options: [
      { externalId: "M1.2-OPT-1", textDe: "Keine angestellten Mitarbeitenden (Einzelunternehmer)", points: 0, order: 1 },
      { externalId: "M1.2-OPT-2", textDe: "1–5 angestellte Mitarbeitende", points: 0, order: 2 },
      { externalId: "M1.2-OPT-3", textDe: "6–10 angestellte Mitarbeitende", points: 0, order: 3 },
      { externalId: "M1.2-OPT-4", textDe: "11–25 angestellte Mitarbeitende", points: 0, order: 4 },
      { externalId: "M1.2-OPT-5", textDe: "26–50 angestellte Mitarbeitende", points: 0, order: 5 },
      { externalId: "M1.2-OPT-6", textDe: "51–100 angestellte Mitarbeitende", points: 0, order: 6 },
      { externalId: "M1.2-OPT-7", textDe: "101–250 angestellte Mitarbeitende", points: 0, order: 7 },
      { externalId: "M1.2-OPT-8", textDe: "Mehr als 250 angestellte Mitarbeitende", points: 0, order: 8 },
    ],
  },
  {
    externalId: "M1.3",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 102,
    isRequired: true,
    intent: "Anzahl Standorte erfassen — beeinflusst Branching in M6 und M7",
    questionDe: "An wie vielen Standorten ist Ihr Unternehmen tätig?",
    options: [
      { externalId: "M1.3-OPT-1", textDe: "1 Standort", points: 0, order: 1 },
      { externalId: "M1.3-OPT-2", textDe: "2–3 Standorte", points: 0, order: 2 },
      { externalId: "M1.3-OPT-3", textDe: "4–10 Standorte", points: 0, order: 3 },
      { externalId: "M1.3-OPT-4", textDe: "Mehr als 10 Standorte", points: 0, order: 4 },
    ],
  },
  {
    externalId: "M1.4",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    activationConds: [{ type: "SCORE_MODE", mode: "MULTI_SELECT" }],
    order: 103,
    isRequired: true,
    intent: "Arbeitsweise erfassen — Mehrfachauswahl, bestimmt Aktivierung M5.1",
    questionDe: "Wie arbeiten Ihre Mitarbeitenden hauptsächlich? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "M1.4-OPT-1", textDe: "Büro / Innendienst", points: 0, order: 1 },
      { externalId: "M1.4-OPT-2", textDe: "Außendienst / beim Kunden vor Ort", points: 0, order: 2 },
      { externalId: "M1.4-OPT-3", textDe: "Schichtbetrieb", points: 0, order: 3 },
      { externalId: "M1.4-OPT-4", textDe: "Homeoffice / Remote", points: 0, order: 4 },
      { externalId: "M1.4-OPT-5", textDe: "Wechselnde Einsatzorte", points: 0, order: 5 },
    ],
  },
  {
    externalId: "M1.5",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 104,
    isRequired: true,
    intent: "Funktion des Gesprächspartners erfassen — Kontext für Empfehlungsformulierung",
    questionDe: "In welcher Funktion sind Sie im Unternehmen tätig?",
    options: [
      { externalId: "M1.5-OPT-1", textDe: "Geschäftsführung / Inhaber", points: 0, order: 1 },
      { externalId: "M1.5-OPT-2", textDe: "Teamleitung / Abteilungsleitung", points: 0, order: 2 },
      { externalId: "M1.5-OPT-3", textDe: "Verwaltung / Back-Office", points: 0, order: 3 },
      { externalId: "M1.5-OPT-4", textDe: "IT / Digitalisierungsverantwortliche/r", points: 0, order: 4 },
      { externalId: "M1.5-OPT-5", textDe: "Sonstiges", points: 0, order: 5 },
    ],
  },
  {
    externalId: "M1.6",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 105,
    isRequired: true,
    intent: "Hauptverantwortlichen für interne Abläufe/Digitalisierung erfassen — Branching M4",
    questionDe: "Wer ist in Ihrem Unternehmen hauptsächlich für interne Abläufe und Digitalisierung verantwortlich?",
    options: [
      { externalId: "M1.6-OPT-1", textDe: "Geschäftsführung / Inhaber", points: 0, order: 1 },
      { externalId: "M1.6-OPT-2", textDe: "Verwaltung / Back-Office", points: 0, order: 2 },
      { externalId: "M1.6-OPT-3", textDe: "Teamleitung / Abteilungsleitung", points: 0, order: 3 },
      { externalId: "M1.6-OPT-4", textDe: "Mehrere Personen gemeinsam", points: 0, order: 4 },
      { externalId: "M1.6-OPT-5", textDe: "Keine klare Zuständigkeit", points: 0, order: 5 },
    ],
  },
  {
    externalId: "M1.7",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 106,
    isRequired: true,
    intent: "E-Mail- und Kalenderlösung erfassen — Systemlandschaft M5.8",
    questionDe: "Welche E-Mail- und Kalenderlösung nutzen Sie im Unternehmen?",
    options: [
      { externalId: "M1.7-OPT-1", textDe: "Microsoft 365 (Outlook, Teams)", points: 0, order: 1 },
      { externalId: "M1.7-OPT-2", textDe: "Google Workspace (Gmail, Google Calendar)", points: 0, order: 2 },
      { externalId: "M1.7-OPT-3", textDe: "Andere Lösung (bitte angeben)", points: 0, order: 3 },
      { externalId: "M1.7-OPT-4", textDe: "Keine einheitliche Lösung", points: 0, order: 4 },
    ],
  },
  {
    externalId: "M1.8",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 107,
    isRequired: true,
    intent: "Kundendatenverwaltung erfassen — Basis für M3 und M5.6",
    questionDe: "Wie verwalten Sie aktuell Ihre Kundendaten?",
    options: [
      { externalId: "M1.8-OPT-1", textDe: "CRM-System (bitte angeben welches)", points: 0, order: 1 },
      { externalId: "M1.8-OPT-2", textDe: "Excel / Tabellen", points: 0, order: 2 },
      { externalId: "M1.8-OPT-3", textDe: "Papier / Karteikarten", points: 0, order: 3 },
      { externalId: "M1.8-OPT-4", textDe: "Gar nicht zentral erfasst", points: 0, order: 4 },
    ],
  },
  {
    externalId: "M1.9",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 108,
    isRequired: true,
    intent: "Zeiterfassungsmethode erfassen — Basis für M5.2",
    questionDe: "Wie erfassen Sie die Arbeitszeiten Ihrer Mitarbeitenden?",
    activationConds: HAS_EMPLOYEES,
    options: [
      { externalId: "M1.9-OPT-1", textDe: "Papier / Stundenzettel", points: 0, order: 1 },
      { externalId: "M1.9-OPT-2", textDe: "Excel / Tabellen", points: 0, order: 2 },
      { externalId: "M1.9-OPT-3", textDe: "Digitale Zeiterfassungssoftware (bitte angeben welche)", points: 0, order: 3 },
      { externalId: "M1.9-OPT-4", textDe: "Über Einsatzplanungssoftware integriert", points: 0, order: 4 },
      { externalId: "M1.9-OPT-5", textDe: "Gar nicht digital erfasst", points: 0, order: 5 },
    ],
  },
  {
    externalId: "M1.10",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 109,
    isRequired: true,
    intent: "Einsatz-/Dienstplanungsmethode erfassen — Basis für M5.1",
    questionDe: "Wie erstellen und verwalten Sie aktuell Einsatz- oder Dienstpläne?",
    options: [
      { externalId: "M1.10-OPT-1", textDe: "Papier / handschriftlich", points: 0, order: 1 },
      { externalId: "M1.10-OPT-2", textDe: "Excel / Tabellen", points: 0, order: 2 },
      { externalId: "M1.10-OPT-3", textDe: "Separate Planungssoftware (bitte angeben welche)", points: 0, order: 3 },
      { externalId: "M1.10-OPT-4", textDe: "Keine Dienstplanung notwendig", points: 0, order: 4 },
    ],
  },
  {
    externalId: "M1.11",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    activationConds: [{ type: "SCORE_MODE", mode: "MULTI_SELECT" }],
    order: 110,
    isRequired: true,
    intent: "Interne Kommunikationskanäle erfassen — Basis für M7",
    questionDe: "Über welche Kanäle kommunizieren Sie intern mit Ihren Mitarbeitenden? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "M1.11-OPT-1", textDe: "WhatsApp / WhatsApp Business", points: 0, order: 1 },
      { externalId: "M1.11-OPT-2", textDe: "Microsoft Teams / Slack", points: 0, order: 2 },
      { externalId: "M1.11-OPT-3", textDe: "Telefon", points: 0, order: 3 },
      { externalId: "M1.11-OPT-4", textDe: "E-Mail", points: 0, order: 4 },
      { externalId: "M1.11-OPT-5", textDe: "Persönlich / vor Ort", points: 0, order: 5 },
      { externalId: "M1.11-OPT-6", textDe: "Andere Kanäle", points: 0, order: 6 },
    ],
  },
  {
    externalId: "M1.12",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 111,
    isRequired: true,
    intent: "KI-Nutzung erfassen — Basis für M5.9",
    questionDe: "Nutzen Sie in Ihrem Unternehmen bereits KI-Tools (z.B. ChatGPT, Copilot, etc.)?",
    options: [
      { externalId: "M1.12-OPT-1", textDe: "Nein, noch nicht", points: 0, order: 1 },
      { externalId: "M1.12-OPT-2", textDe: "Ja, gelegentlich privat/einzelne Mitarbeitende", points: 0, order: 2 },
      { externalId: "M1.12-OPT-3", textDe: "Ja, regelmäßig in einzelnen Bereichen", points: 0, order: 3 },
      { externalId: "M1.12-OPT-4", textDe: "Ja, unternehmensweit eingesetzt (welche Anwendungen?)", points: 0, order: 4 },
    ],
  },
  {
    externalId: "M1.13",
    moduleNumber: 1,
    area: "profil",
    phase: "BLUEPRINT_M1",
    questionType: "A",
    order: 112,
    isRequired: false,
    intent: "Weitere Software erfassen — vervollständigt Systemlandschaft für M5.8",
    questionDe: "Welche weiteren Software-Tools oder digitalen Systeme setzen Sie regelmäßig im Unternehmen ein? (Freitext)",
    options: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 2 – Prozessqualität (25% Gesamtgewicht, Typ B, 0–50 Punkte)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M2.1",
    moduleNumber: 2,
    area: "prozessqualitaet",
    phase: "BLUEPRINT_M2",
    questionType: "B",
    order: 200,
    isRequired: true,
    intent: "Prozessdokumentationsgrad erfassen",
    questionDe: "Wie gut sind die wichtigsten Abläufe in Ihrem Unternehmen dokumentiert?",
    options: [
      { externalId: "M2.1-OPT-1", textDe: "Gar nicht — läuft alles aus dem Kopf oder mündlich", points: 0, order: 1 },
      { externalId: "M2.1-OPT-2", textDe: "Teilweise mündlich weitergegeben, aber kaum schriftlich", points: 10, order: 2 },
      { externalId: "M2.1-OPT-3", textDe: "Teilweise schriftlich, aber nicht vollständig", points: 25, order: 3 },
      { externalId: "M2.1-OPT-4", textDe: "Größtenteils dokumentiert", points: 40, order: 4 },
      { externalId: "M2.1-OPT-5", textDe: "Vollständig dokumentiert und gepflegt", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M2.2",
    moduleNumber: 2,
    area: "prozessqualitaet",
    phase: "BLUEPRINT_M2",
    questionType: "B",
    order: 201,
    isRequired: true,
    intent: "Häufigkeit von Mehrfacherfassung erfassen",
    questionDe: "Wie häufig werden dieselben Informationen an mehreren Stellen manuell eingetragen (Mehrfacherfassung)?",
    options: [
      { externalId: "M2.2-OPT-1", textDe: "Sehr häufig — ist tägliche Realität", points: 0, order: 1 },
      { externalId: "M2.2-OPT-2", textDe: "Häufig", points: 15, order: 2 },
      { externalId: "M2.2-OPT-3", textDe: "Gelegentlich", points: 30, order: 3 },
      { externalId: "M2.2-OPT-4", textDe: "Selten", points: 40, order: 4 },
      { externalId: "M2.2-OPT-5", textDe: "Nie — einmalige Eingabe, alles verbunden", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M2.3",
    moduleNumber: 2,
    area: "prozessqualitaet",
    phase: "BLUEPRINT_M2",
    questionType: "B",
    order: 202,
    isRequired: true,
    intent: "Fehlerrate durch manuelle Abläufe erfassen",
    questionDe: "Wie häufig entstehen Fehler oder Probleme durch manuelle Abläufe (vergessene Schritte, Übertragungsfehler, etc.)?",
    options: [
      { externalId: "M2.3-OPT-1", textDe: "Täglich", points: 0, order: 1 },
      { externalId: "M2.3-OPT-2", textDe: "Mehrmals pro Woche", points: 10, order: 2 },
      { externalId: "M2.3-OPT-3", textDe: "Wöchentlich", points: 25, order: 3 },
      { externalId: "M2.3-OPT-4", textDe: "Selten", points: 40, order: 4 },
      { externalId: "M2.3-OPT-5", textDe: "Fast nie", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M2.4",
    moduleNumber: 2,
    area: "prozessqualitaet",
    phase: "BLUEPRINT_M2",
    questionType: "B",
    order: 203,
    isRequired: true,
    intent: "Einarbeitungsaufwand neue Mitarbeitende erfassen",
    questionDe: "Wie einfach ist es, neue Mitarbeitende in bestehende Abläufe einzuarbeiten?",
    activationConds: HAS_EMPLOYEES,
    options: [
      { externalId: "M2.4-OPT-1", textDe: "Sehr schwierig — dauert Monate, viel Wissenstransfer nötig", points: 0, order: 1 },
      { externalId: "M2.4-OPT-2", textDe: "Eher schwierig", points: 15, order: 2 },
      { externalId: "M2.4-OPT-3", textDe: "Mittel — dauert einige Wochen", points: 30, order: 3 },
      { externalId: "M2.4-OPT-4", textDe: "Einfach — gut strukturierte Einarbeitung", points: 40, order: 4 },
      { externalId: "M2.4-OPT-5", textDe: "Sehr einfach — digitale Prozesse und Onboarding vorhanden", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M2.5",
    moduleNumber: 2,
    area: "prozessqualitaet",
    phase: "BLUEPRINT_M2",
    questionType: "B",
    order: 204,
    isRequired: true,
    intent: "Transparenz Bearbeitungsstand erfassen",
    questionDe: "Wie transparent ist der aktuelle Bearbeitungsstand von Aufgaben und Vorgängen für alle Beteiligten?",
    options: [
      { externalId: "M2.5-OPT-1", textDe: "Gar nicht — man muss immer nachfragen", points: 0, order: 1 },
      { externalId: "M2.5-OPT-2", textDe: "Nur durch Nachfragen erkennbar", points: 10, order: 2 },
      { externalId: "M2.5-OPT-3", textDe: "Teilweise — bei manchen Themen sichtbar", points: 25, order: 3 },
      { externalId: "M2.5-OPT-4", textDe: "Meist erkennbar", points: 40, order: 4 },
      { externalId: "M2.5-OPT-5", textDe: "Jederzeit digital einsehbar", points: 50, order: 5 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 3 – Vertriebsstruktur (20% Gesamtgewicht, Typ B, 0–50 Punkte)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M3.1",
    moduleNumber: 3,
    area: "vertriebsstruktur",
    phase: "BLUEPRINT_M3",
    questionType: "B",
    order: 300,
    isRequired: true,
    intent: "Lead-Erfassungsprozess bewerten",
    questionDe: "Wie werden neue Kundenanfragen und Leads bei Ihnen erfasst?",
    options: [
      { externalId: "M3.1-OPT-1", textDe: "Gar nicht zentral — jeder handhabt es selbst", points: 0, order: 1 },
      { externalId: "M3.1-OPT-2", textDe: "Per E-Mail, keine einheitliche Erfassung", points: 10, order: 2 },
      { externalId: "M3.1-OPT-3", textDe: "In Excel oder Listen", points: 20, order: 3 },
      { externalId: "M3.1-OPT-4", textDe: "Im CRM-System", points: 40, order: 4 },
      { externalId: "M3.1-OPT-5", textDe: "CRM mit automatischen Eingangsrouten und Benachrichtigungen", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M3.2",
    moduleNumber: 3,
    area: "vertriebsstruktur",
    phase: "BLUEPRINT_M3",
    questionType: "B",
    order: 301,
    isRequired: true,
    intent: "Angebotsworkflow bewerten",
    questionDe: "Wie läuft die Angebotserstellung und Nachverfolgung bei Ihnen ab?",
    options: [
      { externalId: "M3.2-OPT-1", textDe: "Vollständig manuell, jedes Angebot von Grund auf neu", points: 0, order: 1 },
      { externalId: "M3.2-OPT-2", textDe: "Vorlagen vorhanden, aber keine Nachverfolgung", points: 15, order: 2 },
      { externalId: "M3.2-OPT-3", textDe: "Teilweise digital, ohne einheitlichen Prozess", points: 30, order: 3 },
      { externalId: "M3.2-OPT-4", textDe: "Digital mit klaren Prozessen und Verantwortlichkeiten", points: 40, order: 4 },
      { externalId: "M3.2-OPT-5", textDe: "Automatisierter Workflow mit Genehmigung und Versand", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M3.3",
    moduleNumber: 3,
    area: "vertriebsstruktur",
    phase: "BLUEPRINT_M3",
    questionType: "B",
    order: 302,
    isRequired: true,
    intent: "Überblick über Verkaufschancen bewerten",
    questionDe: "Wie behalten Sie den Überblick über aktuelle Verkaufschancen und deren Status?",
    options: [
      { externalId: "M3.3-OPT-1", textDe: "Gar nicht — kein systematischer Überblick", points: 0, order: 1 },
      { externalId: "M3.3-OPT-2", textDe: "Notizen und Excel", points: 15, order: 2 },
      { externalId: "M3.3-OPT-3", textDe: "Teilweise digital, ohne einheitliche Pipeline", points: 30, order: 3 },
      { externalId: "M3.3-OPT-4", textDe: "CRM mit Verkaufspipeline", points: 40, order: 4 },
      { externalId: "M3.3-OPT-5", textDe: "CRM mit Pipeline und regelmäßigen Auswertungen", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M3.4",
    moduleNumber: 3,
    area: "vertriebsstruktur",
    phase: "BLUEPRINT_M3",
    questionType: "B",
    order: 303,
    isRequired: true,
    intent: "Kundennachfass-Prozess bewerten",
    questionDe: "Wie systematisch fassen Sie bei Interessenten und Kunden nach?",
    options: [
      { externalId: "M3.4-OPT-1", textDe: "Gar nicht — kein aktives Nachfassen", points: 0, order: 1 },
      { externalId: "M3.4-OPT-2", textDe: "Nur wenn der Kunde von sich aus meldet", points: 15, order: 2 },
      { externalId: "M3.4-OPT-3", textDe: "Teilweise — abhängig von der Person", points: 30, order: 3 },
      { externalId: "M3.4-OPT-4", textDe: "Feste Prozesse und Verantwortlichkeiten", points: 40, order: 4 },
      { externalId: "M3.4-OPT-5", textDe: "Automatisierte Follow-up-Sequenzen im CRM", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M3.5",
    moduleNumber: 3,
    area: "vertriebsstruktur",
    phase: "BLUEPRINT_M3",
    questionType: "B",
    order: 304,
    isRequired: true,
    intent: "Transparenz über Kundenanfragen bewerten",
    questionDe: "Wie transparent ist der Status aktueller Kundenanfragen für alle relevanten Mitarbeitenden?",
    options: [
      { externalId: "M3.5-OPT-1", textDe: "Gar nicht — nur die bearbeitende Person weiß es", points: 0, order: 1 },
      { externalId: "M3.5-OPT-2", textDe: "Nur durch Nachfragen", points: 10, order: 2 },
      { externalId: "M3.5-OPT-3", textDe: "Teilweise sichtbar", points: 25, order: 3 },
      { externalId: "M3.5-OPT-4", textDe: "Meist erkennbar für Beteiligte", points: 40, order: 4 },
      { externalId: "M3.5-OPT-5", textDe: "Jederzeit digital für alle einsehbar", points: 50, order: 5 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 4 – Führungsstruktur (15% Gesamtgewicht, Typ B, 0–50 Punkte)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M4.1",
    moduleNumber: 4,
    area: "fuehrungsstruktur",
    phase: "BLUEPRINT_M4",
    questionType: "B",
    order: 400,
    isRequired: true,
    intent: "Klarheit der Verantwortlichkeiten bewerten",
    questionDe: "Wie klar sind Verantwortlichkeiten und Zuständigkeiten in Ihrem Unternehmen geregelt?",
    options: [
      { externalId: "M4.1-OPT-1", textDe: "Gar nicht klar — alles läuft über die Geschäftsführung", points: 0, order: 1 },
      { externalId: "M4.1-OPT-2", textDe: "Teilweise klar, aber viele Überschneidungen", points: 15, order: 2 },
      { externalId: "M4.1-OPT-3", textDe: "Größtenteils klar", points: 30, order: 3 },
      { externalId: "M4.1-OPT-4", textDe: "Klar definiert", points: 40, order: 4 },
      { externalId: "M4.1-OPT-5", textDe: "Vollständig dokumentiert und für alle einsehbar", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M4.2",
    moduleNumber: 4,
    area: "fuehrungsstruktur",
    phase: "BLUEPRINT_M4",
    questionType: "B",
    order: 401,
    isRequired: true,
    intent: "Entscheidungs- und Freigabestruktur bewerten",
    questionDe: "Wie werden Entscheidungen und Freigaben in Ihrem Unternehmen gehandhabt?",
    options: [
      { externalId: "M4.2-OPT-1", textDe: "Alles läuft durch die Geschäftsführung", points: 0, order: 1 },
      { externalId: "M4.2-OPT-2", textDe: "Überwiegend durch die Geschäftsführung", points: 15, order: 2 },
      { externalId: "M4.2-OPT-3", textDe: "Je nach Thema unterschiedlich delegiert", points: 30, order: 3 },
      { externalId: "M4.2-OPT-4", textDe: "Klar delegiert mit definierten Entscheidungsgrenzen", points: 40, order: 4 },
      { externalId: "M4.2-OPT-5", textDe: "Digitale Freigabeprozesse mit klaren Regeln", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M4.3",
    moduleNumber: 4,
    area: "fuehrungsstruktur",
    phase: "BLUEPRINT_M4",
    questionType: "B",
    order: 402,
    isRequired: true,
    intent: "Transparenz über Aufgaben und Projekte bewerten",
    questionDe: "Wie gut sehen Führungskräfte und Mitarbeitende den Status laufender Aufgaben und Projekte?",
    options: [
      { externalId: "M4.3-OPT-1", textDe: "Gar nicht — nur durch direkte Nachfrage", points: 0, order: 1 },
      { externalId: "M4.3-OPT-2", textDe: "Nur durch Nachfragen erkennbar", points: 10, order: 2 },
      { externalId: "M4.3-OPT-3", textDe: "Teilweise sichtbar", points: 25, order: 3 },
      { externalId: "M4.3-OPT-4", textDe: "Überwiegend sichtbar", points: 40, order: 4 },
      { externalId: "M4.3-OPT-5", textDe: "Jederzeit digital für alle einsehbar", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M4.4",
    moduleNumber: 4,
    area: "fuehrungsstruktur",
    phase: "BLUEPRINT_M4",
    questionType: "B",
    order: 403,
    isRequired: true,
    intent: "Aufgabenverteilungsprozess bewerten",
    questionDe: "Wie werden Aufgaben und Verantwortlichkeiten an Mitarbeitende übertragen?",
    activationConds: HAS_EMPLOYEES,
    options: [
      { externalId: "M4.4-OPT-1", textDe: "Mündlich — keine schriftliche Dokumentation", points: 0, order: 1 },
      { externalId: "M4.4-OPT-2", textDe: "Per E-Mail oder WhatsApp", points: 15, order: 2 },
      { externalId: "M4.4-OPT-3", textDe: "Teilweise über Software-Tools", points: 30, order: 3 },
      { externalId: "M4.4-OPT-4", textDe: "Digital mit klaren Verantwortlichkeiten und Fristen", points: 40, order: 4 },
      { externalId: "M4.4-OPT-5", textDe: "Automatisierte Zuweisung mit Tracking und Erinnerungen", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M4.5",
    moduleNumber: 4,
    area: "fuehrungsstruktur",
    phase: "BLUEPRINT_M4",
    questionType: "B",
    order: 404,
    isRequired: true,
    intent: "Personenabhängigkeit und Wissenskonzentration bewerten",
    questionDe: "Wie stark hängt der Betrieb von einzelnen Schlüsselpersonen ab (Wissen, Kontakte, Entscheidungen)?",
    options: [
      { externalId: "M4.5-OPT-1", textDe: "Sehr stark — ohne eine Person würde vieles stillstehen", points: 0, order: 1 },
      { externalId: "M4.5-OPT-2", textDe: "Eher stark", points: 15, order: 2 },
      { externalId: "M4.5-OPT-3", textDe: "Teilweise", points: 30, order: 3 },
      { externalId: "M4.5-OPT-4", textDe: "Gering — Wissen ist dokumentiert und verteilt", points: 40, order: 4 },
      { externalId: "M4.5-OPT-5", textDe: "Kaum — vollständig dokumentiert, mehrere können vertreten", points: 50, order: 5 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 5 – Automatisierungsgrad (15% Gesamtgewicht)
  // Interne Normalisierung: nur aktive Gruppen fließen ein
  // ═══════════════════════════════════════════════════════════════════════════

  // ── 5.1 Dienst- und Einsatzplanung (15% intern) ───────────────────────────
  {
    externalId: "5.1.1",
    moduleNumber: 5,
    groupCode: "5.1",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_FIELD_OR_SHIFT,
    order: 510,
    isRequired: true,
    intent: "Digitalisierungsstand Dienstplanung — Reifegrad",
    questionDe: "Wie erstellen Sie aktuell Dienst- oder Einsatzpläne?",
    options: [
      { externalId: "5.1.1-OPT-1", textDe: "Papier oder mündlich", points: 0, order: 1 },
      { externalId: "5.1.1-OPT-2", textDe: "Excel oder Tabellen", points: 20, order: 2 },
      { externalId: "5.1.1-OPT-3", textDe: "Separate Dienstplanungssoftware (nicht integriert)", points: 60, order: 3 },
      { externalId: "5.1.1-OPT-4", textDe: "Integrierte Software mit Teilautomatisierung", points: 80, order: 4 },
      { externalId: "5.1.1-OPT-5", textDe: "Weitgehend automatisch auf Basis von Regeln und Verfügbarkeiten", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.1.2",
    moduleNumber: 5,
    groupCode: "5.1",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_FIELD_OR_SHIFT,
      { type: "SCORE_GT", ref: "5.1.1", threshold: 0 },
    ],
    order: 511,
    isRequired: false,
    intent: "Manueller Aufwand Planung — Nutzenpotenzial",
    questionDe: "Wie lange dauert die Erstellung eines typischen Wochen- oder Schichtplans?",
    options: [
      { externalId: "5.1.2-OPT-1", textDe: "Mehr als 8 Stunden", points: 0, order: 1 },
      { externalId: "5.1.2-OPT-2", textDe: "4–8 Stunden", points: 25, order: 2 },
      { externalId: "5.1.2-OPT-3", textDe: "1–4 Stunden", points: 50, order: 3 },
      { externalId: "5.1.2-OPT-4", textDe: "Weniger als 1 Stunde", points: 75, order: 4 },
      { externalId: "5.1.2-OPT-5", textDe: "Nahezu automatisch — kaum manueller Aufwand", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.1.3",
    moduleNumber: 5,
    groupCode: "5.1",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_FIELD_OR_SHIFT,
    order: 512,
    isRequired: true,
    intent: "Fehler- und Reibungsverluste — Dringlichkeit",
    questionDe: "Wie häufig kommt es zu kurzfristigen Änderungen an bereits erstellten Plänen?",
    options: [
      { externalId: "5.1.3-OPT-1", textDe: "Täglich", points: 0, order: 1 },
      { externalId: "5.1.3-OPT-2", textDe: "Mehrmals pro Woche", points: 20, order: 2 },
      { externalId: "5.1.3-OPT-3", textDe: "Wöchentlich", points: 45, order: 3 },
      { externalId: "5.1.3-OPT-4", textDe: "Selten", points: 75, order: 4 },
      { externalId: "5.1.3-OPT-5", textDe: "Fast nie", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.1.3-a",
    moduleNumber: 5,
    groupCode: "5.1",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.1.3",
    activationConds: [...HAS_FIELD_OR_SHIFT, { type: "SCORE_LTE", ref: "5.1.3", threshold: 20 }, { type: "SCORE_MODE", mode: "MULTI_SELECT" }],
    order: 513,
    isRequired: false,
    intent: "Ursachen häufiger Planänderungen — Empfehlungssignal",
    questionDe: "Welches sind die häufigsten Ursachen für die kurzfristigen Planänderungen? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.1.3-a-OPT-1", textDe: "Krankheitsausfälle oder unerwartete Abwesenheiten", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-001", "SOL-W-003"], order: 1 },
      { externalId: "5.1.3-a-OPT-2", textDe: "Neue oder geänderte Kundenaufträge im laufenden Betrieb", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-W-001", "SOL-B-001"], order: 2 },
      { externalId: "5.1.3-a-OPT-3", textDe: "Fehlende oder unvollständige Verfügbarkeitsabfrage im Vorfeld", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-001"], order: 3 },
      { externalId: "5.1.3-a-OPT-4", textDe: "Falsch oder unvollständig erfasste Qualifikationen und Zertifikate", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-005"], order: 4 },
      { externalId: "5.1.3-a-OPT-5", textDe: "Kein Echtzeit-Abgleich zwischen Planungs- und anderen Systemen", points: 0, signalCategory: "CUSTOM_DEVELOPMENT", signalValue: 15, solutionRefs: ["SOL-C-001"], order: 5 },
      { externalId: "5.1.3-a-OPT-6", textDe: "Kommunikationsfehler zwischen disponierender Stelle und Mitarbeitenden", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-W-006"], order: 6 },
    ],
  },
  {
    externalId: "5.1.4",
    moduleNumber: 5,
    groupCode: "5.1",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_FIELD_OR_SHIFT,
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
      { type: "SCORE_CAP", cap: 100 },
    ],
    order: 514,
    isRequired: true,
    intent: "Standardisierbarkeit — Automatisierbarkeit",
    questionDe: "Welche Informationen werden bei der Planerstellung automatisch berücksichtigt? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.1.4-OPT-1", textDe: "Keine der genannten Informationen", points: 0, isExclusive: true, order: 1 },
      { externalId: "5.1.4-OPT-2", textDe: "Verfügbarkeiten der Mitarbeitenden", points: 25, order: 2 },
      { externalId: "5.1.4-OPT-3", textDe: "Gesetzliche Arbeitszeitregeln und Pausenzeiten", points: 25, order: 3 },
      { externalId: "5.1.4-OPT-4", textDe: "Qualifikationen und Zertifikate der Mitarbeitenden", points: 25, order: 4 },
      { externalId: "5.1.4-OPT-5", textDe: "Urlaub und Krankmeldungen", points: 25, order: 5 },
    ],
  },
  {
    externalId: "5.1.5",
    moduleNumber: 5,
    groupCode: "5.1",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_FIELD_OR_SHIFT,
      { type: "SCORE_GT", ref: "5.1.1", threshold: 0 },
    ],
    order: 515,
    isRequired: false,
    intent: "System- und Datenlage — Machbarkeit",
    questionDe: "Wie werden Planänderungen an Mitarbeitende kommuniziert?",
    options: [
      { externalId: "5.1.5-OPT-1", textDe: "Telefonisch oder mündlich", points: 0, order: 1 },
      { externalId: "5.1.5-OPT-2", textDe: "Per WhatsApp oder Messenger", points: 15, order: 2 },
      { externalId: "5.1.5-OPT-3", textDe: "Per E-Mail", points: 35, order: 3 },
      { externalId: "5.1.5-OPT-4", textDe: "Über App oder zentrales System", points: 75, order: 4 },
      { externalId: "5.1.5-OPT-5", textDe: "Automatisch mit Bestätigung durch Mitarbeitende", points: 100, order: 5 },
    ],
  },

  // ── 5.2 Arbeitszeit, Zuschläge und Lohnvorbereitung (15% intern) ──────────
  {
    externalId: "5.2.1",
    moduleNumber: 5,
    groupCode: "5.2",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 520,
    isRequired: true,
    intent: "Digitalisierungsstand Zeiterfassung — Reifegrad",
    questionDe: "Wie werden die Arbeitszeiten Ihrer Mitarbeitenden erfasst?",
    options: [
      { externalId: "5.2.1-OPT-1", textDe: "Papier oder Stundenzettel", points: 0, order: 1 },
      { externalId: "5.2.1-OPT-2", textDe: "Excel oder Tabellen", points: 15, order: 2 },
      { externalId: "5.2.1-OPT-3", textDe: "Digitale Zeiterfassung ohne Integration in andere Systeme", points: 55, order: 3 },
      { externalId: "5.2.1-OPT-4", textDe: "Integriert in Planungs- oder HR-System", points: 90, order: 4 },
      { externalId: "5.2.1-OPT-5", textDe: "Automatisch mit Ausnahmeprüfung und Regelwerk", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.2.2",
    moduleNumber: 5,
    groupCode: "5.2",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_EMPLOYEES,
      { type: "SCORE_GT", ref: "5.2.1", threshold: 0 },
    ],
    order: 521,
    isRequired: false,
    intent: "Manueller Aufwand Prüfung — Nutzenpotenzial",
    questionDe: "Wie werden Abweichungen und Fehler bei der Zeiterfassung geprüft?",
    options: [
      { externalId: "5.2.2-OPT-1", textDe: "Gar nicht", points: 0, order: 1 },
      { externalId: "5.2.2-OPT-2", textDe: "Manuell stichprobenartig", points: 20, order: 2 },
      { externalId: "5.2.2-OPT-3", textDe: "Regelmäßige manuelle Stichproben", points: 40, order: 3 },
      { externalId: "5.2.2-OPT-4", textDe: "Regelbasiert mit automatischen Warnmeldungen", points: 80, order: 4 },
      { externalId: "5.2.2-OPT-5", textDe: "Vollständig automatisch", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.2.3-G",
    moduleNumber: 5,
    groupCode: "5.2",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isGating: true,
    activationConds: HAS_EMPLOYEES,
    order: 522,
    isRequired: true,
    intent: "Gating: Ob Zuschläge/Überstunden relevant sind — steuert Aktivierung 5.2.3",
    questionDe: "Werden in Ihrem Unternehmen Lohnzuschläge, Überstunden oder Plus- und Minusstunden erfasst und berechnet?",
    options: [
      { externalId: "5.2.3-G-OPT-1", textDe: "Ja, regelmäßig", points: 0, order: 1 },
      { externalId: "5.2.3-G-OPT-2", textDe: "Ja, gelegentlich", points: 0, order: 2 },
      { externalId: "5.2.3-G-OPT-3", textDe: "Nein", points: 0, order: 3 },
      { externalId: "5.2.3-G-OPT-4", textDe: "Weiß ich nicht", points: 0, order: 4 },
    ],
  },
  {
    externalId: "5.2.3",
    moduleNumber: 5,
    groupCode: "5.2",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_EMPLOYEES,
      { type: "ANSWER_IS", ref: "5.2.3-G", optionExternalIds: ["5.2.3-G-OPT-1", "5.2.3-G-OPT-2"] },
    ],
    order: 523,
    isRequired: false,
    intent: "Standardisierbarkeit Zuschlagsberechnung — Automatisierbarkeit",
    questionDe: "Wie werden Lohnzuschläge, Überstunden und Plus-/Minusstunden berechnet?",
    options: [
      { externalId: "5.2.3-OPT-1", textDe: "Vollständig manuell", points: 0, order: 1 },
      { externalId: "5.2.3-OPT-2", textDe: "Mit Excel", points: 20, order: 2 },
      { externalId: "5.2.3-OPT-3", textDe: "Mit separater Software", points: 60, order: 3 },
      { externalId: "5.2.3-OPT-4", textDe: "Automatisch berechnet", points: 90, order: 4 },
      { externalId: "5.2.3-OPT-5", textDe: "Automatisch + Freigabe + Export an Lohnbuchhaltung", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.2.4",
    moduleNumber: 5,
    groupCode: "5.2",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 524,
    isRequired: true,
    intent: "System- und Datenlage Lohnübergabe — Machbarkeit",
    questionDe: "Wie werden lohnrelevante Daten an die Lohnbuchhaltung übergeben?",
    options: [
      { externalId: "5.2.4-OPT-1", textDe: "Manuell per Papier oder Tabelle", points: 0, order: 1 },
      { externalId: "5.2.4-OPT-2", textDe: "Excel oder PDF per E-Mail", points: 25, order: 2 },
      { externalId: "5.2.4-OPT-3", textDe: "Standardexport aus Software", points: 65, order: 3 },
      { externalId: "5.2.4-OPT-4", textDe: "Direkte Schnittstelle zum Lohnprogramm", points: 90, order: 4 },
      { externalId: "5.2.4-OPT-5", textDe: "Vollautomatisch ohne manuelle Eingriffe", points: 100, order: 5 },
    ],
  },

  // ── 5.3 Urlaub, Abwesenheiten und Vertretungen (10% intern) ──────────────
  {
    externalId: "5.3.1",
    moduleNumber: 5,
    groupCode: "5.3",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 530,
    isRequired: true,
    intent: "Digitalisierungsstand Abwesenheitsanträge — Reifegrad",
    questionDe: "Wie werden Urlaubs- und Abwesenheitsanträge eingereicht?",
    options: [
      { externalId: "5.3.1-OPT-1", textDe: "Mündlich, per Papier oder WhatsApp", points: 0, order: 1 },
      { externalId: "5.3.1-OPT-2", textDe: "Per E-Mail", points: 25, order: 2 },
      { externalId: "5.3.1-OPT-3", textDe: "Digitales Formular ohne Integration", points: 55, order: 3 },
      { externalId: "5.3.1-OPT-4", textDe: "Integriert in Personal- oder Planungssystem", points: 85, order: 4 },
      { externalId: "5.3.1-OPT-5", textDe: "Automatisch mit Regelprüfung und Sofortgenehmigung", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.3.2",
    moduleNumber: 5,
    groupCode: "5.3",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: HAS_FIELD_OR_SHIFT_EMPLOYEES,
    order: 531,
    isRequired: false,
    intent: "Fehler- und Reibungsverluste Vertretung — Dringlichkeit",
    questionDe: "Wie werden Vertretungen bei kurzfristigen Ausfällen organisiert?",
    options: [
      { externalId: "5.3.2-OPT-1", textDe: "Telefonkette — manuell alle anrufen", points: 0, order: 1 },
      { externalId: "5.3.2-OPT-2", textDe: "Messenger-Gruppe oder Sammel-WhatsApp", points: 15, order: 2 },
      { externalId: "5.3.2-OPT-3", textDe: "Listen oder Excel mit qualifizierten Vertretungen", points: 30, order: 3 },
      { externalId: "5.3.2-OPT-4", textDe: "Digitale Anfrage an qualifizierte Mitarbeitende", points: 75, order: 4 },
      { externalId: "5.3.2-OPT-5", textDe: "Automatisch priorisiert nach Verfügbarkeit und Qualifikation", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.3.3",
    moduleNumber: 5,
    groupCode: "5.3",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      ...HAS_EMPLOYEES,
      { type: "QUESTION_ASKED", ref: "5.3.1" },
    ],
    order: 532,
    isRequired: false,
    intent: "System- und Datenlage Abwesenheitsintegration — Machbarkeit",
    questionDe: "Werden genehmigte Abwesenheiten automatisch in Dienstplanung und Zeiterfassung übertragen?",
    options: [
      { externalId: "5.3.3-OPT-1", textDe: "Nein — manuelle Übertragung notwendig", points: 0, order: 1 },
      { externalId: "5.3.3-OPT-2", textDe: "Teilweise manuell übertragen", points: 30, order: 2 },
      { externalId: "5.3.3-OPT-3", textDe: "In einem System integriert", points: 65, order: 3 },
      { externalId: "5.3.3-OPT-4", textDe: "Ja, vollständig systemübergreifend", points: 100, order: 4 },
    ],
  },

  // ── 5.4 Interne Kommunikation und Informationsfluss (10% intern) ──────────
  {
    externalId: "5.4.1",
    moduleNumber: 5,
    groupCode: "5.4",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 540,
    isRequired: true,
    intent: "Kanalanzahl Informationsverteilung — Reifegrad",
    questionDe: "Über wie viele verschiedene Kanäle werden wichtige Informationen im Unternehmen verteilt?",
    options: [
      { externalId: "5.4.1-OPT-1", textDe: "Mehr als 5 verschiedene Kanäle", points: 0, order: 1 },
      { externalId: "5.4.1-OPT-2", textDe: "4–5 Kanäle", points: 20, order: 2 },
      { externalId: "5.4.1-OPT-3", textDe: "3 Kanäle", points: 45, order: 3 },
      { externalId: "5.4.1-OPT-4", textDe: "2 Kanäle", points: 70, order: 4 },
      { externalId: "5.4.1-OPT-5", textDe: "1 zentraler Kanal für alle wichtigen Informationen", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.4.2",
    moduleNumber: 5,
    groupCode: "5.4",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 541,
    isRequired: true,
    intent: "Informationsverluste — Dringlichkeit",
    questionDe: "Wie häufig müssen Mitarbeitende Informationen aktiv nachfragen oder aufwendig suchen?",
    options: [
      { externalId: "5.4.2-OPT-1", textDe: "Mehrmals täglich", points: 0, order: 1 },
      { externalId: "5.4.2-OPT-2", textDe: "Täglich", points: 20, order: 2 },
      { externalId: "5.4.2-OPT-3", textDe: "Mehrmals pro Woche", points: 45, order: 3 },
      { externalId: "5.4.2-OPT-4", textDe: "Selten", points: 75, order: 4 },
      { externalId: "5.4.2-OPT-5", textDe: "Nahezu nie — alles zentral und leicht auffindbar", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.4.2-a",
    moduleNumber: 5,
    groupCode: "5.4",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.4.2",
    activationConds: [
      { type: "SCORE_LTE", ref: "5.4.2", threshold: 20 },
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
    ],
    order: 542,
    isRequired: false,
    intent: "Informationsarten nachgefragt — Empfehlungssignal",
    questionDe: "Welche Arten von Informationen werden von Mitarbeitenden am häufigsten aktiv nachgefragt oder aufwendig gesucht? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.4.2-a-OPT-1", textDe: "Aktuelle Dienstpläne, Schichtzeiten oder Einsatzinformationen", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-001", "SOL-W-006"], order: 1 },
      { externalId: "5.4.2-a-OPT-2", textDe: "Kundendaten oder Auftragsinformationen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-001"], order: 2 },
      { externalId: "5.4.2-a-OPT-3", textDe: "Interne Richtlinien, Prozessbeschreibungen oder Betriebshandbücher", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 15, solutionRefs: ["SOL-B-006"], order: 3 },
      { externalId: "5.4.2-a-OPT-4", textDe: "Status laufender Aufgaben oder Projekte", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-003"], order: 4 },
      { externalId: "5.4.2-a-OPT-5", textDe: "Personalinformationen (Urlaub, Erreichbarkeit, Zuständigkeiten)", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-003", "SOL-W-005"], order: 5 },
      { externalId: "5.4.2-a-OPT-6", textDe: "Allgemeine Unternehmensinformationen und Ankündigungen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 5, solutionRefs: ["SOL-B-004", "SOL-W-006"], order: 6 },
    ],
  },
  {
    externalId: "5.4.3",
    moduleNumber: 5,
    groupCode: "5.4",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 543,
    isRequired: true,
    intent: "Nachweisbarkeit und Versionierung — Standardisierbarkeit",
    questionDe: "Sind wichtige Mitteilungen für alle Mitarbeitenden nachweisbar, versioniert und leicht auffindbar?",
    options: [
      { externalId: "5.4.3-OPT-1", textDe: "Nein — Informationen gehen verloren oder sind nicht auffindbar", points: 0, order: 1 },
      { externalId: "5.4.3-OPT-2", textDe: "Teilweise", points: 35, order: 2 },
      { externalId: "5.4.3-OPT-3", textDe: "Meistens", points: 70, order: 3 },
      { externalId: "5.4.3-OPT-4", textDe: "Ja, vollständig mit Zugriffshistorie", points: 100, order: 4 },
    ],
  },

  // ── 5.5 Dokumente, Formulare und Freigaben (10% intern) ──────────────────
  {
    externalId: "5.5.1",
    moduleNumber: 5,
    groupCode: "5.5",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 550,
    isRequired: true,
    intent: "Digitalisierungsstand Formulare — Reifegrad",
    questionDe: "Wie werden wiederkehrende Formulare und Anträge in Ihrem Unternehmen bearbeitet?",
    options: [
      { externalId: "5.5.1-OPT-1", textDe: "Papier oder E-Mail ohne festen Prozess", points: 0, order: 1 },
      { externalId: "5.5.1-OPT-2", textDe: "PDF oder Word manuell ausgefüllt", points: 20, order: 2 },
      { externalId: "5.5.1-OPT-3", textDe: "Digitales Formular ohne automatisierten Workflow", points: 55, order: 3 },
      { externalId: "5.5.1-OPT-4", textDe: "Digital mit integriertem Freigabeprozess", points: 85, order: 4 },
      { externalId: "5.5.1-OPT-5", textDe: "Vollständig automatisiert inkl. Benachrichtigung und Archivierung", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.5.2",
    moduleNumber: 5,
    groupCode: "5.5",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 551,
    isRequired: true,
    intent: "Mehrfacherfassung — Fehler- und Reibungsverluste",
    questionDe: "Wie häufig werden dieselben Daten in verschiedene Systeme mehrfach manuell eingetragen?",
    options: [
      { externalId: "5.5.2-OPT-1", textDe: "Sehr häufig — ist tägliche Realität", points: 0, order: 1 },
      { externalId: "5.5.2-OPT-2", textDe: "Häufig", points: 20, order: 2 },
      { externalId: "5.5.2-OPT-3", textDe: "Gelegentlich", points: 45, order: 3 },
      { externalId: "5.5.2-OPT-4", textDe: "Selten", points: 75, order: 4 },
      { externalId: "5.5.2-OPT-5", textDe: "Nie — einmalige Eingabe, alles automatisch verteilt", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.5.2-a",
    moduleNumber: 5,
    groupCode: "5.5",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.5.2",
    activationConds: [
      { type: "SCORE_LTE", ref: "5.5.2", threshold: 20 },
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
    ],
    order: 552,
    isRequired: false,
    intent: "Systeme mit Doppelerfassung — Empfehlungssignal",
    questionDe: "In welchen Bereichen werden dieselben Daten am häufigsten manuell mehrfach erfasst? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.5.2-a-OPT-1", textDe: "Zeiterfassung und Lohnvorbereitung", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-002", "SOL-W-004"], order: 1 },
      { externalId: "5.5.2-a-OPT-2", textDe: "Kundendaten zwischen CRM und anderen Systemen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-001", "SOL-C-001"], order: 2 },
      { externalId: "5.5.2-a-OPT-3", textDe: "Auftrags- und Projektdaten in mehreren Tools parallel", points: 0, signalCategory: "CUSTOM_DEVELOPMENT", signalValue: 15, solutionRefs: ["SOL-C-001", "SOL-B-003"], order: 3 },
      { externalId: "5.5.2-a-OPT-4", textDe: "Personalstammdaten (Adressen, Verträge, Qualifikationen)", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-005", "SOL-B-002"], order: 4 },
      { externalId: "5.5.2-a-OPT-5", textDe: "Rechnungs- und Buchhaltungsdaten", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-005", "SOL-C-001"], order: 5 },
      { externalId: "5.5.2-a-OPT-6", textDe: "Dienstplaninformationen und Kommunikationssystem separat", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-001", "SOL-W-006"], order: 6 },
    ],
  },
  {
    externalId: "5.5.3-G",
    moduleNumber: 5,
    groupCode: "5.5",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isGating: true,
    order: 553,
    isRequired: true,
    intent: "Gating: Ob Freigabeprozesse vorhanden sind — steuert Aktivierung 5.5.3",
    questionDe: "Gibt es in Ihrem Unternehmen wiederkehrende Freigaben oder Genehmigungsprozesse?",
    options: [
      { externalId: "5.5.3-G-OPT-1", textDe: "Ja (z.B. Urlaubsanträge, Rechnungsfreigaben, Angebotsfreigaben)", points: 0, order: 1 },
      { externalId: "5.5.3-G-OPT-2", textDe: "Nein", points: 0, order: 2 },
      { externalId: "5.5.3-G-OPT-3", textDe: "Weiß ich nicht", points: 0, order: 3 },
    ],
  },
  {
    externalId: "5.5.3",
    moduleNumber: 5,
    groupCode: "5.5",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "ANSWER_IS", ref: "5.5.3-G", optionExternalIds: ["5.5.3-G-OPT-1"] },
    ],
    order: 554,
    isRequired: false,
    intent: "Freigabedokumentation — System- und Datenlage",
    questionDe: "Wie werden Freigaben und Genehmigungen dokumentiert und nachgehalten?",
    options: [
      { externalId: "5.5.3-OPT-1", textDe: "Mündlich — keine Dokumentation", points: 0, order: 1 },
      { externalId: "5.5.3-OPT-2", textDe: "Per E-Mail oder Chat", points: 20, order: 2 },
      { externalId: "5.5.3-OPT-3", textDe: "In Liste oder Ticket-System", points: 55, order: 3 },
      { externalId: "5.5.3-OPT-4", textDe: "Digitaler Genehmigungsworkflow mit Benachrichtigung", points: 85, order: 4 },
      { externalId: "5.5.3-OPT-5", textDe: "Automatisch mit Eskalation, Audit-Trail und Archivierung", points: 100, order: 5 },
    ],
  },

  // ── 5.6 Vertrieb und Kundenprozesse (10% intern) ─────────────────────────
  {
    externalId: "5.6-G",
    moduleNumber: 5,
    groupCode: "5.6",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isGating: true,
    order: 560,
    isRequired: true,
    intent: "Gating: Ob Vertrieb/Kundenakquise relevant ist — steuert Aktivierung Gruppe 5.6",
    questionDe: "Bearbeitet Ihr Unternehmen Kundenanfragen, Verkaufschancen, Angebote oder wiederkehrende Auftragsabwicklung?",
    options: [
      { externalId: "5.6-G-OPT-1", textDe: "Ja, regelmäßig", points: 0, order: 1 },
      { externalId: "5.6-G-OPT-2", textDe: "Ja, gelegentlich", points: 0, order: 2 },
      { externalId: "5.6-G-OPT-3", textDe: "Nein", points: 0, order: 3 },
    ],
  },
  {
    externalId: "5.6.1",
    moduleNumber: 5,
    groupCode: "5.6",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "ANSWER_IS", ref: "5.6-G", optionExternalIds: ["5.6-G-OPT-1", "5.6-G-OPT-2"] },
    ],
    order: 561,
    isRequired: false,
    intent: "Digitalisierungsstand Lead-Erfassung — Reifegrad",
    questionDe: "Wie werden Kundenanfragen und Leads bei Ihnen erfasst und weiterverarbeitet?",
    options: [
      { externalId: "5.6.1-OPT-1", textDe: "Nicht zentral — jeder handhabt es anders", points: 0, order: 1 },
      { externalId: "5.6.1-OPT-2", textDe: "Per E-Mail oder Excel", points: 20, order: 2 },
      { externalId: "5.6.1-OPT-3", textDe: "CRM ohne automatisierte Workflows", points: 60, order: 3 },
      { externalId: "5.6.1-OPT-4", textDe: "CRM mit Workflows und Benachrichtigungen", points: 85, order: 4 },
      { externalId: "5.6.1-OPT-5", textDe: "End-to-End automatisiert (Eingang bis Angebot)", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.6.2",
    moduleNumber: 5,
    groupCode: "5.6",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "ANSWER_IS", ref: "5.6-G", optionExternalIds: ["5.6-G-OPT-1", "5.6-G-OPT-2"] },
    ],
    order: 562,
    isRequired: false,
    intent: "Angebotsworkflow und Follow-up-Steuerung — Standardisierbarkeit",
    questionDe: "Wie werden Angebote, Follow-ups und nächste Schritte im Vertrieb gesteuert?",
    options: [
      { externalId: "5.6.2-OPT-1", textDe: "Individuell manuell — kein einheitlicher Prozess", points: 0, order: 1 },
      { externalId: "5.6.2-OPT-2", textDe: "Vorlagen vorhanden, aber keine Nachverfolgung", points: 25, order: 2 },
      { externalId: "5.6.2-OPT-3", textDe: "Teilweise über CRM", points: 60, order: 3 },
      { externalId: "5.6.2-OPT-4", textDe: "Regelbasiert mit definierten Prozessschritten", points: 90, order: 4 },
      { externalId: "5.6.2-OPT-5", textDe: "Vollständig integriert mit Auswertungen und Reporting", points: 100, order: 5 },
    ],
  },

  // ── 5.7 Verwaltung und wiederkehrende Backoffice-Aufgaben (10% intern) ────
  {
    externalId: "5.7.1",
    moduleNumber: 5,
    groupCode: "5.7",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 570,
    isRequired: true,
    intent: "Manueller Verwaltungsaufwand — Nutzenpotenzial",
    questionDe: "Wie viele wiederkehrende Verwaltungsaufgaben werden täglich oder wöchentlich manuell ausgeführt?",
    options: [
      { externalId: "5.7.1-OPT-1", textDe: "Mehr als 20", points: 0, order: 1 },
      { externalId: "5.7.1-OPT-2", textDe: "11–20", points: 20, order: 2 },
      { externalId: "5.7.1-OPT-3", textDe: "6–10", points: 45, order: 3 },
      { externalId: "5.7.1-OPT-4", textDe: "1–5", points: 75, order: 4 },
      { externalId: "5.7.1-OPT-5", textDe: "Nahezu keine — weitgehend automatisiert", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.7.1-a",
    moduleNumber: 5,
    groupCode: "5.7",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.7.1",
    activationConds: [
      { type: "SCORE_LTE", ref: "5.7.1", threshold: 45 },
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
      { type: "MAX_SELECTIONS", max: 3 },
    ],
    order: 571,
    isRequired: false,
    intent: "Top-3 manuelle Verwaltungsaufgaben — Empfehlungssignal",
    questionDe: "Welche drei Verwaltungsaufgaben binden den größten manuellen Aufwand pro Woche? (Bitte bis zu 3 auswählen)",
    options: [
      { externalId: "5.7.1-a-OPT-1", textDe: "Dienst-/Einsatzplanung erstellen und kommunizieren", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-001"], order: 1 },
      { externalId: "5.7.1-a-OPT-2", textDe: "Arbeitszeiten erfassen, prüfen und zusammenfassen", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-002"], order: 2 },
      { externalId: "5.7.1-a-OPT-3", textDe: "Lohnvorbereitung und Stundenabrechnung aufbereiten", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-004"], order: 3 },
      { externalId: "5.7.1-a-OPT-4", textDe: "Angebote erstellen und an Kunden versenden", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-004", "SOL-B-001"], order: 4 },
      { externalId: "5.7.1-a-OPT-5", textDe: "Rechnungen schreiben und Zahlungseingänge verfolgen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-005"], order: 5 },
      { externalId: "5.7.1-a-OPT-6", textDe: "Urlaubs- und Abwesenheitsanträge bearbeiten und dokumentieren", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-003"], order: 6 },
      { externalId: "5.7.1-a-OPT-7", textDe: "Mitarbeiterdokumente verwalten und aktualisieren", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-005", "SOL-B-002"], order: 7 },
      { externalId: "5.7.1-a-OPT-8", textDe: "Termine koordinieren und Erinnerungen manuell auslösen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-004", "SOL-B-003"], order: 8 },
      { externalId: "5.7.1-a-OPT-9", textDe: "Kundenanfragen bearbeiten und intern weiterleiten", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-004", "SOL-B-001"], order: 9 },
      { externalId: "5.7.1-a-OPT-10", textDe: "Auswertungen und Berichte manuell erstellen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-003"], order: 10 },
    ],
  },
  {
    externalId: "5.7.2",
    moduleNumber: 5,
    groupCode: "5.7",
    internalWeight: 0.10,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 572,
    isRequired: true,
    intent: "Trigger-Mechanismen für Aufgaben — Standardisierbarkeit",
    questionDe: "Wie werden Termine, Erinnerungen und wiederkehrende Aufgaben ausgelöst?",
    options: [
      { externalId: "5.7.2-OPT-1", textDe: "Manuell aus dem Gedächtnis — keine systematische Steuerung", points: 0, order: 1 },
      { externalId: "5.7.2-OPT-2", textDe: "Über Kalender oder händisch geführte Listen", points: 35, order: 2 },
      { externalId: "5.7.2-OPT-3", textDe: "Aufgabenmanagement-Software mit manueller Eingabe", points: 65, order: 3 },
      { externalId: "5.7.2-OPT-4", textDe: "Automatisierte Trigger und Workflows", points: 100, order: 4 },
    ],
  },

  // ── 5.8 Systemlandschaft, Schnittstellen und Datenflüsse (15% intern) ─────
  {
    externalId: "5.8.1",
    moduleNumber: 5,
    groupCode: "5.8",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 580,
    isRequired: true,
    intent: "Systemvernetzung — Reifegrad",
    questionDe: "Wie gut sind Ihre wichtigsten Softwaresysteme miteinander vernetzt?",
    options: [
      { externalId: "5.8.1-OPT-1", textDe: "Gar nicht — alle Systeme funktionieren isoliert", points: 0, order: 1 },
      { externalId: "5.8.1-OPT-2", textDe: "Nur manuelle Datenexporte und -importe", points: 20, order: 2 },
      { externalId: "5.8.1-OPT-3", textDe: "Einzelne Schnittstellen vorhanden", points: 55, order: 3 },
      { externalId: "5.8.1-OPT-4", textDe: "Weitgehend integriert", points: 85, order: 4 },
      { externalId: "5.8.1-OPT-5", textDe: "Zentrale Datenflüsse zwischen allen relevanten Systemen", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.8.2",
    moduleNumber: 5,
    groupCode: "5.8",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 581,
    isRequired: true,
    intent: "Prozesslücken in Systemlandschaft — Fehler- und Reibungsverluste",
    questionDe: "Gibt es geschäftskritische Prozesse, die mit Ihrer vorhandenen Software nicht oder nur unzureichend abgebildet werden können?",
    options: [
      { externalId: "5.8.2-OPT-1", textDe: "Ja, mehrere geschäftskritische Prozesse", points: 0, order: 1 },
      { externalId: "5.8.2-OPT-2", textDe: "Ja, 1–2 wichtige Prozesse", points: 30, order: 2 },
      { externalId: "5.8.2-OPT-3", textDe: "Nur Sonderfälle, keine kritischen Lücken", points: 70, order: 3 },
      { externalId: "5.8.2-OPT-4", textDe: "Nein — alle relevanten Prozesse abgedeckt", points: 100, order: 4 },
    ],
  },
  {
    externalId: "5.8.2-a",
    moduleNumber: 5,
    groupCode: "5.8",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.8.2",
    activationConds: [
      { type: "SCORE_LTE", ref: "5.8.2", threshold: 30 },
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
    ],
    order: 582,
    isRequired: false,
    intent: "Konkrete Prozesslücken — Empfehlungssignal (Custom-Development-Indikator)",
    questionDe: "Welche Prozesse können mit der vorhandenen Software nicht oder nur unzureichend abgebildet werden? (Mehrfachauswahl möglich; branchenspezifische Besonderheiten im Freitext ergänzbar)",
    options: [
      { externalId: "5.8.2-a-OPT-1", textDe: "Dienstplanung unter Berücksichtigung aller Anforderungen (Qualifikationen, Regeln, Verfügbarkeiten)", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-001"], order: 1 },
      { externalId: "5.8.2-a-OPT-2", textDe: "Automatisierte Zeiterfassung mit Lohnübergabe", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-002", "SOL-W-004"], order: 2 },
      { externalId: "5.8.2-a-OPT-3", textDe: "Kundenspezifische Angebots- und Vertragsprozesse", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-004", "SOL-C-002"], order: 3 },
      { externalId: "5.8.2-a-OPT-4", textDe: "Qualifikations-, Zertifikats- und Fristenverwaltung der Mitarbeitenden", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-005"], order: 4 },
      { externalId: "5.8.2-a-OPT-5", textDe: "Übergreifende Auswertungen und Reporting", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-C-003"], order: 5 },
      { externalId: "5.8.2-a-OPT-6", textDe: "Branchenspezifische Sonderlogik (Freitext)", points: 0, signalCategory: "CUSTOM_DEVELOPMENT", signalValue: 20, solutionRefs: ["SOL-C-002"], order: 6 },
    ],
  },
  {
    externalId: "5.8.3",
    moduleNumber: 5,
    groupCode: "5.8",
    internalWeight: 0.15,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    order: 583,
    isRequired: true,
    intent: "Datenverfügbarkeit für Automatisierungen — Machbarkeit",
    questionDe: "Sind die für Automatisierungen relevanten Daten strukturiert und maschinell verfügbar?",
    options: [
      { externalId: "5.8.3-OPT-1", textDe: "Nein — Daten kaum strukturiert vorhanden", points: 0, order: 1 },
      { externalId: "5.8.3-OPT-2", textDe: "Teilweise, aber uneinheitlich", points: 30, order: 2 },
      { externalId: "5.8.3-OPT-3", textDe: "Größtenteils vorhanden", points: 70, order: 3 },
      { externalId: "5.8.3-OPT-4", textDe: "Ja, vollständig und einheitlich strukturiert", points: 100, order: 4 },
    ],
  },
  {
    externalId: "5.8.3-a",
    moduleNumber: 5,
    groupCode: "5.8",
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "A",
    isFollowUp: true,
    parentExternalId: "5.8.3",
    activationConds: [
      { type: "SCORE_LTE", ref: "5.8.3", threshold: 30 },
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
    ],
    order: 584,
    isRequired: false,
    intent: "Unstrukturierte Datenquellen — Aufwandsfaktor Empfehlungssystem",
    questionDe: "In welchen Bereichen liegen relevante Daten unstrukturiert, uneinheitlich oder nicht maschinell verarbeitbar vor? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.8.3-a-OPT-1", textDe: "Mitarbeiterstammdaten (Papier, Excel, verteilt auf verschiedene Orte)", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-005", "SOL-B-002"], order: 1 },
      { externalId: "5.8.3-a-OPT-2", textDe: "Zeiterfassungsdaten (Zettel, Fotos, handschriftliche Listen)", points: 0, signalCategory: "WORKFORCE", signalValue: 15, solutionRefs: ["SOL-W-002"], order: 2 },
      { externalId: "5.8.3-a-OPT-3", textDe: "Kundendaten und Kontaktinformationen", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-001"], order: 3 },
      { externalId: "5.8.3-a-OPT-4", textDe: "Auftrags- und Projektdaten", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-003", "SOL-C-004"], order: 4 },
      { externalId: "5.8.3-a-OPT-5", textDe: "Qualifikationsnachweise und Zertifikate", points: 0, signalCategory: "WORKFORCE", signalValue: 10, solutionRefs: ["SOL-W-005"], order: 5 },
      { externalId: "5.8.3-a-OPT-6", textDe: "Finanz- und Buchhaltungsdaten", points: 0, signalCategory: "BEWAEHRTE_LOESUNG", signalValue: 10, solutionRefs: ["SOL-B-005"], order: 6 },
    ],
  },

  // ── 5.9 KI-Nutzung und wissensbasierte Tätigkeiten (5% intern) ───────────
  {
    externalId: "5.9.1",
    moduleNumber: 5,
    groupCode: "5.9",
    internalWeight: 0.05,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "SCORE_MODE", mode: "MULTI_SELECT" },
      { type: "SCORE_CAP", cap: 100 },
    ],
    order: 590,
    isRequired: true,
    intent: "KI-Nutzungsgrad — Reifegrad",
    questionDe: "Für welche Aufgaben wird KI heute in Ihrem Unternehmen eingesetzt? (Mehrfachauswahl möglich)",
    options: [
      { externalId: "5.9.1-OPT-1", textDe: "Gar nicht", points: 0, isExclusive: true, order: 1 },
      { externalId: "5.9.1-OPT-2", textDe: "Texterstellung und Formulierung", points: 20, order: 2 },
      { externalId: "5.9.1-OPT-3", textDe: "Recherche und Informationsauswertung", points: 25, order: 3 },
      { externalId: "5.9.1-OPT-4", textDe: "Dokumentenverarbeitung und -analyse", points: 50, order: 4 },
      { externalId: "5.9.1-OPT-5", textDe: "Wissenssuche und interne Auskunft", points: 60, order: 5 },
      { externalId: "5.9.1-OPT-6", textDe: "Automatisierte Prozesse und Workflows", points: 80, order: 6 },
      { externalId: "5.9.1-OPT-7", textDe: "Unternehmensweit geregelt und eingesetzt", points: 100, order: 7 },
    ],
  },
  {
    externalId: "5.9.2",
    moduleNumber: 5,
    groupCode: "5.9",
    internalWeight: 0.05,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "ANSWER_NOT_IS", ref: "5.9.1", optionExternalIds: ["5.9.1-OPT-1"] },
    ],
    order: 591,
    isRequired: false,
    intent: "Wissensbasierter Arbeitsaufwand — Nutzenpotenzial",
    questionDe: "Wie viele Stunden pro Woche werden im Unternehmen für Text-, Recherche- und Dokumentationsaufgaben aufgewendet?",
    options: [
      { externalId: "5.9.2-OPT-1", textDe: "Mehr als 40 Stunden pro Woche", points: 0, order: 1 },
      { externalId: "5.9.2-OPT-2", textDe: "20–40 Stunden", points: 20, order: 2 },
      { externalId: "5.9.2-OPT-3", textDe: "8–20 Stunden", points: 45, order: 3 },
      { externalId: "5.9.2-OPT-4", textDe: "1–8 Stunden", points: 75, order: 4 },
      { externalId: "5.9.2-OPT-5", textDe: "Nahezu keine", points: 100, order: 5 },
    ],
  },
  {
    externalId: "5.9.3",
    moduleNumber: 5,
    groupCode: "5.9",
    internalWeight: 0.05,
    area: "automatisierungsgrad",
    phase: "BLUEPRINT_M5",
    questionType: "B",
    activationConds: [
      { type: "ANSWER_NOT_IS", ref: "5.9.1", optionExternalIds: ["5.9.1-OPT-1"] },
    ],
    order: 592,
    isRequired: false,
    intent: "KI-Governance — Standardisierbarkeit",
    questionDe: "Gibt es in Ihrem Unternehmen verbindliche Regeln für Datenschutz, Qualität und Freigaben beim KI-Einsatz?",
    options: [
      { externalId: "5.9.3-OPT-1", textDe: "Nein", points: 0, order: 1 },
      { externalId: "5.9.3-OPT-2", textDe: "Informelle Regeln, aber nichts dokumentiert", points: 30, order: 2 },
      { externalId: "5.9.3-OPT-3", textDe: "Teilweise dokumentierte Richtlinien", points: 65, order: 3 },
      { externalId: "5.9.3-OPT-4", textDe: "Vollständig geregelt und für alle verbindlich", points: 100, order: 4 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 6 – Unternehmensstruktur (10% Gesamtgewicht, Typ B, 0–50 Punkte)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M6.1",
    moduleNumber: 6,
    area: "unternehmensstruktur",
    phase: "BLUEPRINT_M6",
    questionType: "B",
    order: 600,
    isRequired: true,
    intent: "Organisationsstruktur und -dokumentation bewerten",
    questionDe: "Wie gut ist Ihre Unternehmensstruktur organisiert und dokumentiert?",
    options: [
      { externalId: "M6.1-OPT-1", textDe: "Keine klare Struktur vorhanden", points: 0, order: 1 },
      { externalId: "M6.1-OPT-2", textDe: "Teilweise vorhanden, aber nicht dokumentiert", points: 15, order: 2 },
      { externalId: "M6.1-OPT-3", textDe: "Überwiegend klar, teilweise dokumentiert", points: 30, order: 3 },
      { externalId: "M6.1-OPT-4", textDe: "Gut strukturiert", points: 40, order: 4 },
      { externalId: "M6.1-OPT-5", textDe: "Vollständig dokumentiert und regelmäßig aktualisiert", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M6.2",
    moduleNumber: 6,
    area: "unternehmensstruktur",
    phase: "BLUEPRINT_M6",
    questionType: "B",
    order: 601,
    isRequired: true,
    intent: "Personenabhängigkeit bewerten",
    questionDe: "Wie stark ist Ihr Unternehmen von einzelnen Personen abhängig (Wissen, Kontakte, Entscheidungen)?",
    options: [
      { externalId: "M6.2-OPT-1", textDe: "Sehr stark — ohne Schlüsselpersonen würde vieles stillstehen", points: 0, order: 1 },
      { externalId: "M6.2-OPT-2", textDe: "Eher stark", points: 15, order: 2 },
      { externalId: "M6.2-OPT-3", textDe: "Teilweise", points: 30, order: 3 },
      { externalId: "M6.2-OPT-4", textDe: "Gering — Wissen ist verteilt und dokumentiert", points: 40, order: 4 },
      { externalId: "M6.2-OPT-5", textDe: "Kaum — vollständig skalierbar und dokumentiert", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M6.3",
    moduleNumber: 6,
    area: "unternehmensstruktur",
    phase: "BLUEPRINT_M6",
    questionType: "B",
    order: 602,
    isRequired: true,
    intent: "Skalierbarkeit und Expansionsfähigkeit bewerten",
    questionDe: "Wie einfach ist es, neue Standorte, Teams oder Mitarbeitende in bestehende Strukturen zu integrieren?",
    options: [
      { externalId: "M6.3-OPT-1", textDe: "Sehr schwierig — jede Erweiterung ist ein Kraftakt", points: 0, order: 1 },
      { externalId: "M6.3-OPT-2", textDe: "Aufwendig", points: 15, order: 2 },
      { externalId: "M6.3-OPT-3", textDe: "Mit einigem Aufwand möglich", points: 30, order: 3 },
      { externalId: "M6.3-OPT-4", textDe: "Relativ einfach dank klarer Prozesse", points: 40, order: 4 },
      { externalId: "M6.3-OPT-5", textDe: "Standardisiert und dokumentiert — schnelle Integration", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M6.4",
    moduleNumber: 6,
    area: "unternehmensstruktur",
    phase: "BLUEPRINT_M6",
    questionType: "B",
    order: 603,
    isRequired: true,
    intent: "Standardisierung Onboarding-Prozesse bewerten",
    questionDe: "Gibt es standardisierte Abläufe für die Einarbeitung neuer Mitarbeitender?",
    activationConds: HAS_EMPLOYEES,
    options: [
      { externalId: "M6.4-OPT-1", textDe: "Nein — jede Einarbeitung läuft anders", points: 0, order: 1 },
      { externalId: "M6.4-OPT-2", textDe: "Teilweise standardisiert", points: 20, order: 2 },
      { externalId: "M6.4-OPT-3", textDe: "Überwiegend standardisiert", points: 40, order: 3 },
      { externalId: "M6.4-OPT-4", textDe: "Vollständig standardisiert und dokumentiert", points: 50, order: 4 },
    ],
  },
  {
    externalId: "M6.5",
    moduleNumber: 6,
    area: "unternehmensstruktur",
    phase: "BLUEPRINT_M6",
    questionType: "B",
    order: 604,
    isRequired: true,
    intent: "Unternehmenskennzahlen und Transparenz bewerten",
    questionDe: "Wie leicht sind relevante Unternehmenskennzahlen (Umsatz, Kosten, Auslastung) für Sie einsehbar?",
    options: [
      { externalId: "M6.5-OPT-1", textDe: "Gar nicht — keine systematische Auswertung", points: 0, order: 1 },
      { externalId: "M6.5-OPT-2", textDe: "Nur durch manuelle Auswertung möglich", points: 15, order: 2 },
      { externalId: "M6.5-OPT-3", textDe: "Teilweise digital abrufbar", points: 30, order: 3 },
      { externalId: "M6.5-OPT-4", textDe: "Digital mit regelmäßigen Auswertungen", points: 40, order: 4 },
      { externalId: "M6.5-OPT-5", textDe: "Echtzeit-Dashboards jederzeit abrufbar", points: 50, order: 5 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 7 – Kommunikation (10% Gesamtgewicht, Typ B, 0–50 Punkte, 7 Fragen)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M7.1",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    activationConds: [{ type: "SCORE_MODE", mode: "MAX" }],
    order: 700,
    isRequired: true,
    intent: "Kommunikationskanäle bewerten — Score = höchste gewählte Option",
    questionDe: "Welche Kommunikationskanäle nutzen Sie hauptsächlich im Unternehmen? (Wählen Sie die am stärksten genutzten)",
    options: [
      { externalId: "M7.1-OPT-1", textDe: "Persönlich / vor Ort", points: 10, order: 1 },
      { externalId: "M7.1-OPT-2", textDe: "Telefon", points: 15, order: 2 },
      { externalId: "M7.1-OPT-3", textDe: "WhatsApp / Messenger", points: 20, order: 3 },
      { externalId: "M7.1-OPT-4", textDe: "E-Mail", points: 30, order: 4 },
      { externalId: "M7.1-OPT-5", textDe: "Teams / Slack / Kommunikationsplattform", points: 45, order: 5 },
      { externalId: "M7.1-OPT-6", textDe: "Zentrale Plattform mit definierten Kommunikationsprozessen", points: 50, order: 6 },
    ],
  },
  {
    externalId: "M7.2",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 701,
    isRequired: true,
    intent: "Häufigkeit von Informationsverlusten bewerten",
    questionDe: "Wie häufig gehen wichtige Informationen verloren oder erreichen nicht alle relevanten Personen?",
    options: [
      { externalId: "M7.2-OPT-1", textDe: "Sehr häufig — fast täglich", points: 0, order: 1 },
      { externalId: "M7.2-OPT-2", textDe: "Häufig", points: 15, order: 2 },
      { externalId: "M7.2-OPT-3", textDe: "Gelegentlich", points: 30, order: 3 },
      { externalId: "M7.2-OPT-4", textDe: "Selten", points: 40, order: 4 },
      { externalId: "M7.2-OPT-5", textDe: "Nie — alle sind immer informiert", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M7.3",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 702,
    isRequired: true,
    intent: "Kurzfristige Änderungskommunikation bewerten",
    questionDe: "Wie kommunizieren Sie kurzfristige Änderungen (Termine, Aufgaben, Pläne) an Ihre Mitarbeitenden?",
    options: [
      { externalId: "M7.3-OPT-1", textDe: "Telefonisch oder per WhatsApp — keine einheitliche Methode", points: 10, order: 1 },
      { externalId: "M7.3-OPT-2", textDe: "Per E-Mail", points: 20, order: 2 },
      { externalId: "M7.3-OPT-3", textDe: "Über Gruppen-Chat", points: 35, order: 3 },
      { externalId: "M7.3-OPT-4", textDe: "Über zentrales System mit Bestätigung", points: 50, order: 4 },
    ],
  },
  {
    externalId: "M7.4",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 703,
    isRequired: true,
    intent: "Informationszugang und -transparenz bewerten",
    questionDe: "Wissen Ihre Mitarbeitenden immer, wo sie aktuelle und relevante Informationen finden?",
    options: [
      { externalId: "M7.4-OPT-1", textDe: "Nein — oft unklar, wo Infos sind", points: 0, order: 1 },
      { externalId: "M7.4-OPT-2", textDe: "Teilweise", points: 20, order: 2 },
      { externalId: "M7.4-OPT-3", textDe: "Meistens", points: 40, order: 3 },
      { externalId: "M7.4-OPT-4", textDe: "Ja — alles zentral zugänglich", points: 50, order: 4 },
    ],
  },
  {
    externalId: "M7.5",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 704,
    isRequired: true,
    intent: "Transparenz über Aufgaben und Prozesse bewerten",
    questionDe: "Wie transparent sind laufende Aufgaben und Prozesse für alle Beteiligten?",
    options: [
      { externalId: "M7.5-OPT-1", textDe: "Gar nicht — nur durch Nachfragen erkennbar", points: 0, order: 1 },
      { externalId: "M7.5-OPT-2", textDe: "Nur durch Nachfragen", points: 15, order: 2 },
      { externalId: "M7.5-OPT-3", textDe: "Teilweise sichtbar", points: 30, order: 3 },
      { externalId: "M7.5-OPT-4", textDe: "Überwiegend sichtbar", points: 40, order: 4 },
      { externalId: "M7.5-OPT-5", textDe: "Jederzeit digital für alle einsehbar", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M7.6",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 705,
    isRequired: true,
    intent: "Existenz fester Kommunikationsprozesse bewerten",
    questionDe: "Gibt es in Ihrem Unternehmen feste Kommunikationsprozesse (regelmäßige Meetings, Übergaben, Updates)?",
    options: [
      { externalId: "M7.6-OPT-1", textDe: "Nein — läuft alles ad hoc", points: 0, order: 1 },
      { externalId: "M7.6-OPT-2", textDe: "Teilweise — nicht systematisch", points: 20, order: 2 },
      { externalId: "M7.6-OPT-3", textDe: "Ja, aber manuell und informell", points: 35, order: 3 },
      { externalId: "M7.6-OPT-4", textDe: "Ja, standardisiert und digital unterstützt", points: 50, order: 4 },
    ],
  },
  {
    externalId: "M7.7",
    moduleNumber: 7,
    area: "kommunikation",
    phase: "BLUEPRINT_M7",
    questionType: "B",
    order: 706,
    isRequired: true,
    intent: "Zeitaufwand für Rückfragen und Informationssuche bewerten",
    questionDe: "Wie viel Zeit verbringen Ihre Mitarbeitenden täglich mit Rückfragen und der Suche nach Informationen?",
    options: [
      { externalId: "M7.7-OPT-1", textDe: "Mehr als 60 Minuten täglich", points: 0, order: 1 },
      { externalId: "M7.7-OPT-2", textDe: "30–60 Minuten", points: 15, order: 2 },
      { externalId: "M7.7-OPT-3", textDe: "15–30 Minuten", points: 30, order: 3 },
      { externalId: "M7.7-OPT-4", textDe: "Weniger als 15 Minuten", points: 45, order: 4 },
      { externalId: "M7.7-OPT-5", textDe: "Nahezu keine Zeit", points: 50, order: 5 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MODUL 8 – Personalmanagement (5% Gesamtgewicht, Typ B, 0–50 Punkte)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    externalId: "M8.1",
    moduleNumber: 8,
    area: "personalmanagement",
    phase: "BLUEPRINT_M8",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 800,
    isRequired: true,
    intent: "Einarbeitungsstruktur für neue Mitarbeitende bewerten",
    questionDe: "Wie strukturiert ist die Einarbeitung neuer Mitarbeitender?",
    options: [
      { externalId: "M8.1-OPT-1", textDe: "Keine Struktur — lernen durch Beobachten", points: 0, order: 1 },
      { externalId: "M8.1-OPT-2", textDe: "Mündliche Einweisung", points: 15, order: 2 },
      { externalId: "M8.1-OPT-3", textDe: "Teilweise dokumentierte Unterlagen", points: 30, order: 3 },
      { externalId: "M8.1-OPT-4", textDe: "Standardisierter Onboarding-Prozess", points: 40, order: 4 },
      { externalId: "M8.1-OPT-5", textDe: "Digitales Onboarding mit Checklisten und E-Learning", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M8.2",
    moduleNumber: 8,
    area: "personalmanagement",
    phase: "BLUEPRINT_M8",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 801,
    isRequired: true,
    intent: "Mitarbeiterdokumentenverwaltung bewerten",
    questionDe: "Wie werden Mitarbeiterdokumente (Verträge, Zeugnisse, Nachweise) verwaltet?",
    options: [
      { externalId: "M8.2-OPT-1", textDe: "Papier-Akten", points: 0, order: 1 },
      { externalId: "M8.2-OPT-2", textDe: "Lokale Dateien auf einzelnen Rechnern", points: 15, order: 2 },
      { externalId: "M8.2-OPT-3", textDe: "Cloudspeicher ohne Struktur", points: 30, order: 3 },
      { externalId: "M8.2-OPT-4", textDe: "Digital strukturiert mit Ordnersystem", points: 40, order: 4 },
      { externalId: "M8.2-OPT-5", textDe: "Zentrales digitales Personalverwaltungssystem (DMS/HRIS)", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M8.3",
    moduleNumber: 8,
    area: "personalmanagement",
    phase: "BLUEPRINT_M8",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 802,
    isRequired: true,
    intent: "Urlaubsantragsverfahren bewerten",
    questionDe: "Wie werden Urlaubs- und Abwesenheitsanträge in Ihrem Unternehmen bearbeitet?",
    options: [
      { externalId: "M8.3-OPT-1", textDe: "Papier, mündlich oder WhatsApp", points: 0, order: 1 },
      { externalId: "M8.3-OPT-2", textDe: "Per E-Mail", points: 20, order: 2 },
      { externalId: "M8.3-OPT-3", textDe: "Excel oder Tabellen", points: 30, order: 3 },
      { externalId: "M8.3-OPT-4", textDe: "Digitale HR-Software", points: 45, order: 4 },
      { externalId: "M8.3-OPT-5", textDe: "Vollständig digital mit automatischer Freigabe und Kalenderintegration", points: 50, order: 5 },
    ],
  },
  {
    externalId: "M8.4",
    moduleNumber: 8,
    area: "personalmanagement",
    phase: "BLUEPRINT_M8",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 803,
    isRequired: true,
    intent: "Qualifikations- und Fristenverwaltung bewerten",
    questionDe: "Wie verwalten Sie Qualifikationsnachweise, Pflichtschulungen und ablaufende Zertifikate Ihrer Mitarbeitenden?",
    options: [
      { externalId: "M8.4-OPT-1", textDe: "Gar nicht systematisch", points: 0, order: 1 },
      { externalId: "M8.4-OPT-2", textDe: "Excel oder Tabellen", points: 20, order: 2 },
      { externalId: "M8.4-OPT-3", textDe: "Teilweise digital", points: 35, order: 3 },
      { externalId: "M8.4-OPT-4", textDe: "Automatische Erinnerungen und digitale Nachweise", points: 50, order: 4 },
    ],
  },
  {
    externalId: "M8.5",
    moduleNumber: 8,
    area: "personalmanagement",
    phase: "BLUEPRINT_M8",
    questionType: "B",
    activationConds: HAS_EMPLOYEES,
    order: 804,
    isRequired: true,
    intent: "Gesamten Personalverwaltungsaufwand bewerten",
    questionDe: "Wie hoch ist der monatliche manuelle Aufwand für Personalverwaltungsaufgaben?",
    options: [
      { externalId: "M8.5-OPT-1", textDe: "Sehr hoch — bindet mehrere Tage pro Monat", points: 0, order: 1 },
      { externalId: "M8.5-OPT-2", textDe: "Eher hoch", points: 15, order: 2 },
      { externalId: "M8.5-OPT-3", textDe: "Mittel", points: 30, order: 3 },
      { externalId: "M8.5-OPT-4", textDe: "Gering", points: 40, order: 4 },
      { externalId: "M8.5-OPT-5", textDe: "Sehr gering durch digitale Prozesse", points: 50, order: 5 },
    ],
  },
];

// ─── SOLUTION LIBRARY ────────────────────────────────────────────────────────

export const SOLUTIONS = [
  // OKUN Workforce
  { externalId: "SOL-W-001", name: "OKUN Workforce – Dienstplanung", category: "WORKFORCE", description: "Digitale Dienst- und Einsatzplanung mit Verfügbarkeitsmanagement, Qualifikationsprüfung und Mitarbeiter-App.", packageTypes: ["operations", "custom"] },
  { externalId: "SOL-W-002", name: "OKUN Workforce – Zeiterfassung", category: "WORKFORCE", description: "Integrierte digitale Zeiterfassung mit automatischer Abweichungsprüfung und Lohnexport.", packageTypes: ["operations", "custom"] },
  { externalId: "SOL-W-003", name: "OKUN Workforce – Abwesenheitsmanagement", category: "WORKFORCE", description: "Digitaler Urlaubsantragsprozess mit automatischer Regelprüfung, Genehmigungsworkflow und Kalenderintegration.", packageTypes: ["operations", "custom"] },
  { externalId: "SOL-W-004", name: "OKUN Workforce – Lohnvorbereitung", category: "WORKFORCE", description: "Automatisierte Lohnvorbereitung mit Zuschlagsberechnung, Freigabe und direktem Lohnbuchhalter-Export.", packageTypes: ["operations", "custom"] },
  { externalId: "SOL-W-005", name: "OKUN Workforce – Qualifikationsmanagement", category: "WORKFORCE", description: "Verwaltung von Qualifikationsnachweisen und Pflichtzertifikaten mit automatischen Ablaufbenachrichtigungen.", packageTypes: ["operations", "custom"] },
  { externalId: "SOL-W-006", name: "OKUN Workforce – Mitarbeiterkommunikation", category: "WORKFORCE", description: "Zentraler Kommunikationskanal für operative Teams mit Push-Benachrichtigungen und Lesebestätigungen.", packageTypes: ["operations", "custom"] },

  // Bewährte Automatisierungslösungen
  { externalId: "SOL-B-001", name: "CRM-System", category: "BEWAEHRTE_LOESUNG", description: "Einführung eines geeigneten CRM-Systems (z.B. HubSpot, Pipedrive) für zentrale Kundendatenverwaltung, Lead-Tracking und Angebotsnachverfolgung.", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-002", name: "Dokumentenmanagementsystem (DMS)", category: "BEWAEHRTE_LOESUNG", description: "Strukturierte digitale Dokumentenverwaltung und -ablage mit Zugriffsrechten und Versionierung.", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-003", name: "Aufgaben- und Projektmanagement", category: "BEWAEHRTE_LOESUNG", description: "Einführung einer Aufgabenmanagementlösung (z.B. Asana, Monday, Trello) für transparente Aufgabenverteilung und Statusverfolgung.", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-004", name: "Kommunikationsplattform", category: "BEWAEHRTE_LOESUNG", description: "Einheitliche interne Kommunikationsplattform (z.B. Microsoft Teams, Slack) für alle Kanäle.", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-005", name: "Buchhaltungs- und Rechnungssoftware", category: "BEWAEHRTE_LOESUNG", description: "Digitale Buchhaltungs- und Rechnungsstellung mit Steuerberaterschnittstelle (z.B. Lexoffice, sevDesk, DATEV).", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-006", name: "Wissensmanagementsystem / Wiki", category: "BEWAEHRTE_LOESUNG", description: "Zentrale Wissensdatenbank für Prozessdokumentation, Handbücher und Richtlinien (z.B. Notion, Confluence).", packageTypes: ["foundation", "operations", "custom"] },
  { externalId: "SOL-B-007", name: "Digitale Formulare und Workflows", category: "BEWAEHRTE_LOESUNG", description: "Standardisierte digitale Formulare mit automatischen Freigabe-Workflows (z.B. JotForm, Microsoft Forms + Power Automate).", packageTypes: ["foundation", "operations", "custom"] },

  // Custom Development
  { externalId: "SOL-C-001", name: "Systemintegrationen und Schnittstellen", category: "CUSTOM_DEVELOPMENT", description: "Individuelle API-Integrationen zwischen vorhandenen Systemen zur Eliminierung von Medienbrüchen und Doppelerfassung.", packageTypes: ["custom"] },
  { externalId: "SOL-C-002", name: "Branchenspezifische Sonderlösungen", category: "CUSTOM_DEVELOPMENT", description: "Entwicklung individueller Module für branchenspezifische Anforderungen, die durch Standardsoftware nicht abgedeckt werden.", packageTypes: ["custom"] },
  { externalId: "SOL-C-003", name: "Reporting- und BI-Dashboard", category: "CUSTOM_DEVELOPMENT", description: "Maßgeschneidertes Auswertungs-Dashboard mit systemübergreifenden Kennzahlen und Echtzeit-Daten.", packageTypes: ["custom"] },
  { externalId: "SOL-C-004", name: "Eingangsverarbeitung und Vorgangsautomatisierung", category: "CUSTOM_DEVELOPMENT", description: "Eingehende Anfragen werden automatisch ausgelesen, die Daten in die vorhandenen Systeme übernommen, ein Vorgang angelegt, Dokument und Antwort vorbereitet, die zuständige Person informiert und der gesamte Ablauf protokolliert. Der Mensch entscheidet, statt zu übertragen.", packageTypes: ["operations", "custom"] },
];
