-- Add 2FA fields to User model
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorExpiry" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorSentAt" TIMESTAMP(3);
